#! /bin/sh

#sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
dunst -conf ~/.config/dunst/dunstrc &
picom -conf ~/.config/picom/picom.conf &
picom --no-fading-openclose &
kdeconnect-indicator &
nm-applet&
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on
bspc rule -a Microsoft-edge-dev desktop='^1' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a Spotify desktop='^4' follow=on
bspc rule -a Gnome-terminal desktop='^2' follow=on
bspc rule -a zoom desktop='^5' follow=on
bspc rule -a TelegramDesktop desktop='^6' follow=on
bspc rule -a Com.gitlab.newsflash desktop='^6' follow=on
bspc rule -a notion-snap desktop='^7' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
volumeicon &
redshit &
